# Generated by Django 5.0.6 on 2024-06-10 16:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProductTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_created=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('delFlg', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'branch_product_tbl',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GroupProductTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_created=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('delFlg', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'group_product_tbl',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_created=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('delFlg', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'product_tbl',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PropertiesTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_created=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('delFlg', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'properties_tbl',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avata', models.ImageField(upload_to='users/%Y/%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='branchproducttbl',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_branch_product_code_name'),
        ),
        migrations.AddField(
            model_name='groupproducttbl',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.branchproducttbl'),
        ),
        migrations.AddField(
            model_name='producttbl',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.groupproducttbl'),
        ),
        migrations.AddField(
            model_name='propertiestbl',
            name='products',
            field=models.ManyToManyField(to='categories.producttbl'),
        ),
        migrations.AddConstraint(
            model_name='groupproducttbl',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_group_product_code_name'),
        ),
        migrations.AddConstraint(
            model_name='producttbl',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_product_code_name'),
        ),
        migrations.AddConstraint(
            model_name='propertiestbl',
            constraint=models.UniqueConstraint(fields=('code', 'color'), name='unique_properties_code_name'),
        ),
    ]
